name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "Thank you for your pull request. However, you have submitted this PR on the go-packagist organization which is a read-only sub split of `go-packagist/framework`. Please submit your PR on the https://github.com/go-packagist/framework repository.<br><br>Thanks!"