name: Go Test
on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master, feature/* ]
env:
  GOPROXY: "https://proxy.golang.org"

jobs:
  test:
    name: "go test"
    strategy:
      matrix:
        go-version: [ 1.16.x, 1.17.x, 1.18.x, 1.19.x, 1.20.x ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
#        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}

#    services:
#      redis:
#        image: redis
#        options: >-
#          --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
#        ports:
#          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version

      - name: Run tests
        run: go test ./... -v -covermode=atomic -race -coverprofile=coverage.txt

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3