name: Go Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GOPROXY: "https://proxy.golang.org"

jobs:
  test:
    name: "go test"
    strategy:
      matrix:
        go-version: [ 1.16.x, 1.17.x, 1.18.x ]
#        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Services
        run: |
          docker run --name redis -p 6379:6379 -d redis
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test ./... -v -covermode=atomic